// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Mimetype      string                 `protobuf:"bytes,7,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	OldPrice      float32                `protobuf:"fixed32,8,opt,name=oldPrice,proto3" json:"oldPrice,omitempty"`
	Count         int32                  `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`
	Code          string                 `protobuf:"bytes,10,opt,name=code,proto3" json:"code,omitempty"`
	CategoryId    string                 `protobuf:"bytes,11,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Product) GetOldPrice() float32 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *Product) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Product) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type SearchProductByFilterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MinPrice      *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice      *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	CategoryId    *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductByFilterRequest) Reset() {
	*x = SearchProductByFilterRequest{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductByFilterRequest) ProtoMessage() {}

func (x *SearchProductByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductByFilterRequest.ProtoReflect.Descriptor instead.
func (*SearchProductByFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductByFilterRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SearchProductByFilterRequest) GetMinPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *SearchProductByFilterRequest) GetMaxPrice() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxPrice
	}
	return nil
}

func (x *SearchProductByFilterRequest) GetCategoryId() *wrapperspb.StringValue {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

type SearchProductByFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductByFilterResponse) Reset() {
	*x = SearchProductByFilterResponse{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductByFilterResponse) ProtoMessage() {}

func (x *SearchProductByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductByFilterResponse.ProtoReflect.Descriptor instead.
func (*SearchProductByFilterResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *SearchProductByFilterResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIDRequest) Reset() {
	*x = GetProductByIDRequest{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIDRequest) ProtoMessage() {}

func (x *GetProductByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCartByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartByIdResponse) Reset() {
	*x = GetCartByIdResponse{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartByIdResponse) ProtoMessage() {}

func (x *GetCartByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCartByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartByIdResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Products      []*Product             `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	CurrentPrice  float32                `protobuf:"fixed32,3,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    string                 `protobuf:"bytes,7,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CreateProductRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateProductRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UploadProductImgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Img           []byte                 `protobuf:"bytes,2,opt,name=img,proto3" json:"img,omitempty"`
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProductImgRequest) Reset() {
	*x = UploadProductImgRequest{}
	mi := &file_proto_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProductImgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProductImgRequest) ProtoMessage() {}

func (x *UploadProductImgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProductImgRequest.ProtoReflect.Descriptor instead.
func (*UploadProductImgRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *UploadProductImgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadProductImgRequest) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *UploadProductImgRequest) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

type UploadProductImgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProductImgResponse) Reset() {
	*x = UploadProductImgResponse{}
	mi := &file_proto_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProductImgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProductImgResponse) ProtoMessage() {}

func (x *UploadProductImgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProductImgResponse.ProtoReflect.Descriptor instead.
func (*UploadProductImgResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *UploadProductImgResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateProductTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductTitleRequest) Reset() {
	*x = UpdateProductTitleRequest{}
	mi := &file_proto_product_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductTitleRequest) ProtoMessage() {}

func (x *UpdateProductTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductTitleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateProductTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductTitleResponse) Reset() {
	*x = UpdateProductTitleResponse{}
	mi := &file_proto_product_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductTitleResponse) ProtoMessage() {}

func (x *UpdateProductTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductTitleResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductTitleResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductTitleResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice      float32                `protobuf:"fixed32,3,opt,name=oldPrice,proto3" json:"oldPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceRequest) Reset() {
	*x = UpdateProductPriceRequest{}
	mi := &file_proto_product_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceRequest) ProtoMessage() {}

func (x *UpdateProductPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProductPriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductPriceRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductPriceRequest) GetOldPrice() float32 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

type UpdateProductPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceResponse) Reset() {
	*x = UpdateProductPriceResponse{}
	mi := &file_proto_product_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceResponse) ProtoMessage() {}

func (x *UpdateProductPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProductPriceResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogRequest) Reset() {
	*x = DeleteCatalogRequest{}
	mi := &file_proto_product_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogRequest) ProtoMessage() {}

func (x *DeleteCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCatalogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_product_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{16}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_proto_product_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCategoryRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_proto_product_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_proto_product_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{19}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\aproduct\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9d\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\x12\x1a\n" +
	"\bimageUrl\x18\x06 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bmimetype\x18\a \x01(\tR\bmimetype\x12\x1a\n" +
	"\boldPrice\x18\b \x01(\x02R\boldPrice\x12\x14\n" +
	"\x05count\x18\t \x01(\x05R\x05count\x12\x12\n" +
	"\x04code\x18\n" +
	" \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"categoryId\x18\v \x01(\tR\n" +
	"categoryId\"\x82\x02\n" +
	"\x1cSearchProductByFilterRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x127\n" +
	"\bminPrice\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\bminPrice\x127\n" +
	"\bmaxPrice\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\bmaxPrice\x12<\n" +
	"\n" +
	"categoryId\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"categoryId\"M\n" +
	"\x1dSearchProductByFilterResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"'\n" +
	"\x15GetProductByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x13GetCartByIdResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"C\n" +
	"\x13ListProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x88\x01\n" +
	"\x14ListProductsResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12,\n" +
	"\bproducts\x18\x04 \x03(\v2\x10.product.ProductR\bproducts\"\xd2\x01\n" +
	"\x14CreateProductRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\"\n" +
	"\fcurrentPrice\x18\x03 \x01(\x02R\fcurrentPrice\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryId\x18\a \x01(\tR\n" +
	"categoryId\"C\n" +
	"\x15CreateProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"W\n" +
	"\x17UploadProductImgRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03img\x18\x02 \x01(\fR\x03img\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\"6\n" +
	"\x18UploadProductImgResponse\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\"A\n" +
	"\x19UpdateProductTitleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"H\n" +
	"\x1aUpdateProductTitleResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"]\n" +
	"\x19UpdateProductPriceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x1a\n" +
	"\boldPrice\x18\x03 \x01(\x02R\boldPrice\"H\n" +
	"\x1aUpdateProductPriceResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"&\n" +
	"\x14DeleteCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcategoryName\x18\x02 \x01(\tR\fcategoryName\"F\n" +
	"\x15CreateCategoryRequest\x12-\n" +
	"\bcategory\x18\x01 \x01(\v2\x11.product.CategoryR\bcategory\"G\n" +
	"\x16CreateCategoryResponse\x12-\n" +
	"\bcategory\x18\x01 \x01(\v2\x11.product.CategoryR\bcategory\"K\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.product.CategoryR\n" +
	"categories2\xc5\x05\n" +
	"\x0eProductService\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12N\n" +
	"\x0eGetProductByID\x12\x1e.product.GetProductByIDRequest\x1a\x1c.product.GetCartByIdResponse\x12g\n" +
	"\x16SearchProductsByFilter\x12%.product.SearchProductByFilterRequest\x1a&.product.SearchProductByFilterResponse\x12N\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x1e.product.CreateProductResponse\x12W\n" +
	"\x10UploadProductImg\x12 .product.UploadProductImgRequest\x1a!.product.UploadProductImgResponse\x12]\n" +
	"\x12UpdateProductTitle\x12\".product.UpdateProductTitleRequest\x1a#.product.UpdateProductTitleResponse\x12]\n" +
	"\x12UpdateProductPrice\x12\".product.UpdateProductPriceRequest\x1a#.product.UpdateProductPriceResponse\x12F\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteCatalogRequest\x1a\x16.google.protobuf.Empty2\xaf\x01\n" +
	"\x0fCategoryService\x12Q\n" +
	"\x0eCreateCategory\x12\x1e.product.CreateCategoryRequest\x1a\x1f.product.CreateCategoryResponse\x12I\n" +
	"\x0eListCategories\x12\x16.google.protobuf.Empty\x1a\x1f.product.ListCategoriesResponseBJZHgithub.com/IbadT/trans_history_microservice/project-protos/proto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_product_product_proto_goTypes = []any{
	(*Product)(nil),                       // 0: product.Product
	(*SearchProductByFilterRequest)(nil),  // 1: product.SearchProductByFilterRequest
	(*SearchProductByFilterResponse)(nil), // 2: product.SearchProductByFilterResponse
	(*GetProductByIDRequest)(nil),         // 3: product.GetProductByIDRequest
	(*GetCartByIdResponse)(nil),           // 4: product.GetCartByIdResponse
	(*ListProductsRequest)(nil),           // 5: product.ListProductsRequest
	(*ListProductsResponse)(nil),          // 6: product.ListProductsResponse
	(*CreateProductRequest)(nil),          // 7: product.CreateProductRequest
	(*CreateProductResponse)(nil),         // 8: product.CreateProductResponse
	(*UploadProductImgRequest)(nil),       // 9: product.UploadProductImgRequest
	(*UploadProductImgResponse)(nil),      // 10: product.UploadProductImgResponse
	(*UpdateProductTitleRequest)(nil),     // 11: product.UpdateProductTitleRequest
	(*UpdateProductTitleResponse)(nil),    // 12: product.UpdateProductTitleResponse
	(*UpdateProductPriceRequest)(nil),     // 13: product.UpdateProductPriceRequest
	(*UpdateProductPriceResponse)(nil),    // 14: product.UpdateProductPriceResponse
	(*DeleteCatalogRequest)(nil),          // 15: product.DeleteCatalogRequest
	(*Category)(nil),                      // 16: product.Category
	(*CreateCategoryRequest)(nil),         // 17: product.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),        // 18: product.CreateCategoryResponse
	(*ListCategoriesResponse)(nil),        // 19: product.ListCategoriesResponse
	(*wrapperspb.StringValue)(nil),        // 20: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),         // 21: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),                 // 22: google.protobuf.Empty
}
var file_proto_product_product_proto_depIdxs = []int32{
	20, // 0: product.SearchProductByFilterRequest.title:type_name -> google.protobuf.StringValue
	21, // 1: product.SearchProductByFilterRequest.minPrice:type_name -> google.protobuf.Int32Value
	21, // 2: product.SearchProductByFilterRequest.maxPrice:type_name -> google.protobuf.Int32Value
	20, // 3: product.SearchProductByFilterRequest.categoryId:type_name -> google.protobuf.StringValue
	0,  // 4: product.SearchProductByFilterResponse.products:type_name -> product.Product
	0,  // 5: product.GetCartByIdResponse.product:type_name -> product.Product
	0,  // 6: product.ListProductsResponse.products:type_name -> product.Product
	0,  // 7: product.CreateProductResponse.product:type_name -> product.Product
	0,  // 8: product.UpdateProductTitleResponse.product:type_name -> product.Product
	0,  // 9: product.UpdateProductPriceResponse.product:type_name -> product.Product
	16, // 10: product.CreateCategoryRequest.category:type_name -> product.Category
	16, // 11: product.CreateCategoryResponse.category:type_name -> product.Category
	16, // 12: product.ListCategoriesResponse.categories:type_name -> product.Category
	5,  // 13: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	3,  // 14: product.ProductService.GetProductByID:input_type -> product.GetProductByIDRequest
	1,  // 15: product.ProductService.SearchProductsByFilter:input_type -> product.SearchProductByFilterRequest
	7,  // 16: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	9,  // 17: product.ProductService.UploadProductImg:input_type -> product.UploadProductImgRequest
	11, // 18: product.ProductService.UpdateProductTitle:input_type -> product.UpdateProductTitleRequest
	13, // 19: product.ProductService.UpdateProductPrice:input_type -> product.UpdateProductPriceRequest
	15, // 20: product.ProductService.DeleteProduct:input_type -> product.DeleteCatalogRequest
	17, // 21: product.CategoryService.CreateCategory:input_type -> product.CreateCategoryRequest
	22, // 22: product.CategoryService.ListCategories:input_type -> google.protobuf.Empty
	6,  // 23: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	4,  // 24: product.ProductService.GetProductByID:output_type -> product.GetCartByIdResponse
	2,  // 25: product.ProductService.SearchProductsByFilter:output_type -> product.SearchProductByFilterResponse
	8,  // 26: product.ProductService.CreateProduct:output_type -> product.CreateProductResponse
	10, // 27: product.ProductService.UploadProductImg:output_type -> product.UploadProductImgResponse
	12, // 28: product.ProductService.UpdateProductTitle:output_type -> product.UpdateProductTitleResponse
	14, // 29: product.ProductService.UpdateProductPrice:output_type -> product.UpdateProductPriceResponse
	22, // 30: product.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	18, // 31: product.CategoryService.CreateCategory:output_type -> product.CreateCategoryResponse
	19, // 32: product.CategoryService.ListCategories:output_type -> product.ListCategoriesResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
